color = input("enter a color: ")
plueral_noun = input("enter a plueral noun: ")
adj = input("enter an adjective: ")
print("Trees are "+ color)
print(plueral_noun +" are mean")
print("please keep it "+ adj)
